import { useState, useEffect, useRef } from 'react'

// Extended preset loader that combines multiple preset packs
const PRESET_SOURCES = [
  // Base presets (already loaded via butterchurnPresets.min.js)
  { name: 'base', loaded: true },
]

// Extended preset collection - will be populated
let extendedPresets = {}
let extendedKeys = []
let isLoading = false
let loadPromise = null

// Quality preset names (curated list of the best ones)
const QUALITY_PRESETS = [
  // Flexi collection - high quality
  'Flexi, martin + geiss - dedicated to the sherwin maxawow',
  'Flexi - alien fish pond',
  'Flexi - baroque enjoyment',
  'Flexi - bouncing balls [26])
  'Flexi - bouncing fractal 1 [26])
  'Flexi - box of kisses',
  'Flexi - brain coral',
  'Flexi - dancing jelly',
  'Flexi - digital insanity',
  'Flexi - druid',
  'Flexi - flash of inspiration',
  'Flexi - future garden',
  'Flexi - liquid dreams',
  'Flexi - neon space donut',
  'Flexi - space odyssey',
  'Flexi - starlight v2',
  'Flexi - tunnel of the soul',
  'Flexi - underwater tunnel',
  'Flexi - visual cortex',
  'Flexi - wormhole',
  
  // Martin collection - excellent quality
  'martin - crystal palace',
  'martin - reflections on black tiles',
  'martin - the forge',
  'martin - infinity 2',
  'martin - liquid fire',
  'martin - neon space donut',
  'martin - reflections on black tiles',
  'martin - starlight',
  'martin - the forge',
  'martin - tunnel of the soul',
  
  // Geiss collection - classic MilkDrop
  'Geiss - Artifact 01',
  'Geiss - Bas Relief',
  'Geiss - Bass Zoom',
  'Geiss - Big Blue',
  'Geiss - Blobular',
  'Geiss - Bright Amber',
  'Geiss - Cauldron',
  'Geiss - Colored Dots',
  'Geiss - Cosmic Dust',
  'Geiss - Cruzin',
  'Geiss - Dancing Shadows',
  'Geiss - Desert Twilight',
  'Geiss - Dynamic Swirls',
  'Geiss - Earring',
  'Geiss - Eggs',
  'Geiss - Feedback',
  'Geiss - Four Kinds of Amphetamine',
  'Geiss - Glass Dance',
  'Geiss - Glossy Jelly',
  'Geiss - High Fives',
  'Geiss - Iris',
  'Geiss - Liquid Brightness',
  'Geiss - Liquid Color',
  'Geiss - Microbe',
  'Geiss - Mosaic',
  'Geiss - Old Skool',
  'Geiss - Plasma Globe',
  'Geiss - Quasilinear',
  'Geiss - Radioactive',
  'Geiss - Ripple',
  'Geiss - Shockwave',
  'Geiss - Smoke',
  'Geiss - Solar Flare',
  'Geiss - Starfish',
  'Geiss - Surface',
  'Geiss - Swirlie',
  'Geiss - The Tunnel',
  'Geiss - Three Dots',
  'Geiss - Triple Tube',
  'Geiss - Ultra Light',
  'Geiss - Venetian Blinds',
  'Geiss - Window',
  'Geiss - Zigzag',
  
  // Rovastar collection
  'Rovastar - A Million Miles from Earth',
  'Rovastar - Altars of Madness',
  'Rovastar - Babylon',
  'Rovastar - Barbers Pole',
  'Rovastar - Bell Jar',
  'Rovastar - Big Fun',
  'Rovastar - Binary Star System',
  'Rovastar - Blindsided',
  'Rovastar - Braindance',
  'Rovastar - Brilliant Spheres',
  'Rovastar - Chaos In A Box',
  'Rovastar - Clouded Mirror',
  'Rovastar - Color Of The Wheel',
  'Rovastar - Cosmic Echoes',
  'Rovastar - Cosmic Fusion',
  'Rovastar - Crystal Ball',
  'Rovastar - Dark Ritual',
  'Rovastar - DarkStar',
  'Rovastar - Digital Lights',
  'Rovastar - Dream Catcher',
  'Rovastar - Droplets',
  'Rovastar - El-Barb', 
  'Rovastar - Explosive Minds',
  'Rovastar - Eye Of The Storm',
  'Rovastar - Flaring Carnations',
  'Rovastar - Frenzy',
  'Rovastar - Fractopia',
  'Rovastar - Gateway',
  'Rovastar - Hallucinogenic Hydraulics',
  'Rovastar - Hyperspace',
  'Rovastar - Inner Life',
  'Rovastar - Kalideostars',
  'Rovastar - Lake Serenity',
  'Rovastar - Liquid Plastic',
  'Rovastar - Living Fortress',
  'Rovastar - Magic Carpet Ride',
  'Rovastar - Manhattan Project',
  'Rovastar - Multi-Spectrum',
  'Rovastar - Neutrino',
  'Rovastar - Octoplasm',
  'Rovastar - Ocean Machine',
  'Rovastar - Paradise',
  'Rovastar - Photochrome',
  'Rovastar - Pulsing Foetus',
  'Rovastar - Quicksilver',
  'Rovastar - Red Dawn',
  'Rovastar - River Of Light',
  'Rovastar - Rocket Sauce',
  'Rovastar - Saturnine',
  'Rovastar - Shadow Sphere',
  'Rovastar - Silent Rain',
  'Rovastar - Solarized Space',
  'Rovastar - Space Fractal',
  'Rovastar - Space Opera',
  'Rovastar - Starlight Drifter',
  'Rovastar - Starquake',
  'Rovastar - Stormy Skies',
  'Rovastar - Subterranean City',
  'Rovastar - Time To Burn',
  'Rovastar - Tribal Affair',
  'Rovastar - Triquetra',
  'Rovastar - Twisted Brainwave',
  'Rovastar - Unholy Waters',
  'Rovastar - Voyage Into The Unknown',
  'Rovastar - Warp Drive',
  'Rovastar - Water Dance',
  'Rovastar - Wisdom',
  'Rovastar - Xenomorph',
  'Rovastar - Zeitgeist',
  
  // Illusion collection
  'Illusion - Infinite Structure',
  'Illusion - Organic Form',
  'Illusion - Reality',
  'Illusion - Skyward',
  'Illusion - Temple Of Light',
  
  // Unchained collection
  'Unchained - Crimson Reflections',
  'Unchained - Harmony',
  'Unchained - Images of Nature',
  'Unchained - Liquid Space',
  'Unchained - Re-Enter The Dragon',
  'Unchained - Shock Shadow',
  'Unchained - Slipstream',
  'Unchained - Submersion',
  'Unchained - Venus Vortex',
  
  // Zylot collection
  'Zylot - Blade Of Dawn',
  'Zylot - Crystal Ball',
  'Zylot - Dark Side Of The Sun',
  'Zylot - Dark Victory',
  'Zylot - Deformations',
  'Zylot - Essence',
  'Zylot - Ether Storm',
  'Zylot - Event Horizon',
  'Zylot - Fire And Ice',
  'Zylot - Forsaken',
  'Zylot - Fractal Orbit',
  'Zylot - Illumination',
  'Zylot - Into The Ocean',
  'Zylot - Liquid Emperor',
  'Zylot - Planetary Alignment',
  'Zylot - Polar DNA',
  'Zylot - Psychadelic Eye',
  'Zylot - Psychedelic Swirl',
  'Zylot - Solar Dawn',
  'Zylot - Solar Winds',
  'Zylot - Space Garden',
  'Zylot - Spiral Mind',
  'Zylot - Star Dust',
  'Zylot - Starlight Dreams',
  'Zylot - Surface',
  'Zylot - The Beast',
  'Zylot - The Hive',
  'Zylot - The Stars My Destination',
  'Zylot - Tides',
  'Zylot - Trance Plant',
  'Zylot - Voyage',
  'Zylot - Warp Tunnel',
  'Zylot - Zylot',
  
  // Aderrasi collection
  'Aderrasi - Snowflake',
  'Aderrasi - Animus',
  'Aderrasi - Crystal Storm',
  'Aderrasi - Dark Matter',
  'Aderrasi - Gravitation Point',
  'Aderrasi - Hostile Planet',
  'Aderrasi - Raindown',
  'Aderrasi - Rapture',
  'Aderrasi - Saltwater',
  'Aderrasi - Slipstream',
  'Aderrasi - Surface',
  'Aderrasi - Transcendence',
  
  // Krash collection
  'Krash - 4th Dimension',
  'Krash - Fiber Optic',
  'Krash - Life Saver',
  'Krash - Periodic Texture',
  'Krash - RGB Waveform',
  'Krash - Ripple',
  'Krash - Solar Winds',
  'Krash - Timeless',
  'Krash - Windowpane',
  
  // StudioMusic collection
  'StudioMusic - Animal Palace',
  'StudioMusic - Circle Square Triangle',
  'StudioMusic - Driftwood',
  'StudioMusic - Equinox',
  'StudioMusic - Eye Of The Beholder',
  'StudioMusic - Flyover',
  'StudioMusic - Generations',
  'StudioMusic - Lava Lamp',
  'StudioMusic - Light Beams',
  'StudioMusic - Liquid Sunset',
  'StudioMusic - Moebius',
  'StudioMusic - Neon Mind Warp',
  'StudioMusic - Neural Net',
  'StudioMusic - Particle Dreams',
  'StudioMusic - Phosphor',
  'StudioMusic - Rainbow Resonance',
  'StudioMusic - Sacred Geometry',
  'StudioMusic - Solar Meditation',
  'StudioMusic - Starlight Lounge',
  'StudioMusic - Supernova',
  'StudioMusic - Tesseract',
  'StudioMusic - Time Vortex',
  'StudioMusic - Virtual Escape',
  'StudioMusic - Wormhole Express',
  
  // EoS collection
  'EoS - Aurora Borealis',
  'EoS - Binary Dreams',
  'EoS - Crystal Clarity',
  'EoS - Deep Space',
  'EoS - Digital Rain',
  'EoS - Echoes',
  'EoS - Electric Dreams',
  'EoS - Elemental',
  'EoS - Energy Flow',
  'EoS - Fire And Ice',
  'EoS - Flux',
  'EoS - Fractal Garden',
  'EoS - Glass City',
  'EoS - Infinity',
  'EoS - Liquid Light',
  'EoS - Luminous',
  'EoS - Magnetic Fields',
  'EoS - Neon Dreams',
  'EoS - Northern Lights',
  'EoS - Oceanic',
  'EoS - Plasma Storm',
  'EoS - Prism',
  'EoS - Quantum',
  'EoS - Radiance',
  'EoS - Solar Flare',
  'EoS - Sonic Bloom',
  'EoS - Spectrum',
  'EoS - Stardust',
  'EoS - Supernova',
  'EoS - Synchronicity',
  'EoS - Time Warp',
  'EoS - Vortex',
  'EoS - Waveform',
  
  // Various artists collection
  'fiShbRaiN + Flexi - witchcraft',
  'fiShbRaiN - eat the mushroom',
  'fiShbRaiN - enlightened journey',
  'fiShbRaiN - highway to hell',
  'fiShbRaiN - quaver',
  'fiShbRaiN - stupid',
  
  'Phat + Zylot - Skyward',
  'Phat - 3D Swirl',
  'Phat - Aztec Sunset',
  'Phat - Cathedral',
  'Phat - Cosmic Dust',
  'Phat - Emerald Dawn',
  'Phat - Equinox',
  'Phat - Exodus',
  'Phat - Genesis',
  'Phat - Glass Forest',
  'Phat - Hyperdrive',
  'Phat - Infinity',
  'Phat - Into The Void',
  'Phat - Liquid Sky',
  'Phat - Nebula',
  'Phat - Ocean Dreams',
  'Phat - Pandora',
  'Phat - Radiance',
  'Phat - Solar Flare',
  'Phat - Stardust',
  'Phat - The Core',
  'Phat - Time Machine',
  'Phat - Vortex',
  
  'Redi Jedi - Caribbean Sunset',
  'Redi Jedi - Coral Reef',
  'Redi Jedi - Crystal Cave',
  'Redi Jedi - Electric Storm',
  'Redi Jedi - Fire Within',
  'Redi Jedi - Glass Dreams',
  'Redi Jedi - Golden Hour',
  'Redi Jedi - Liquid Gold',
  'Redi Jedi - Moonlight Sonata',
  'Redi Jedi - Northern Lights',
  'Redi Jedi - Ocean Waves',
  'Redi Jedi - Purple Haze',
  'Redi Jedi - Rainbow Bridge',
  'Redi Jedi - Starlight',
  'Redi Jedi - Sunburst',
  'Redi Jedi - Tropical Paradise',
  'Redi Jedi - Waterfall',
  
  // Add more quality presets here...
  
  // Additional curated presets
  'shifter - fractal flythrough',
  'shifter - ghost town',
  'shifter - liquid fire',
  'shifter - matrix cube',
  'shifter - neon city',
  'shifter - plasma tunnel',
  'shifter - spectral waves',
  'shifter - starfield',
  'shifter - wormhole',
  
  'Cope - Brain Freeze',
  'Cope - Burning Chrome',
  'Cope - Chromatic Aberration',
  'Cope - Deep Space Nine',
  'Cope - Electric Sheep',
  'Cope - Event Horizon',
  'Cope - Liquid Dreams',
  'Cope - Mind Melt',
  'Cope - Neon Genesis',
  'Cope - Starlight Express',
  'Cope - Time Dilation',
  'Cope - Warp Speed',
  
  'EviL steVe - Acid Trip',
  'EviL steVe - Bubble Trouble',
  'EviL steVe - Cosmic Slop',
  'EviL steVe - Digital Delight',
  'EviL steVe - Electric Kool-Aid',
  'EviL steVe - Fire Starter',
  'EviL steVe - Glass House',
  'EviL steVe - Heart Of Glass',
  'EviL steVe - Liquid Sky',
  'EviL steVe - Mind Bender',
  'EviL steVe - Neon Nights',
  'EviL steVe - Psychedelic Shack',
  'EviL steVe - Rainbow Connection',
  'EviL steVe - Space Oddity',
  'EviL steVe - Starlight',
  'EviL steVe - Through The Looking Glass',
  'EviL steVe - Time Warp',
  'EviL steVe - Tunnel Vision',
  
  'EMPR - Auroras',
  'EMPR - Binary Code',
  'EMPR - City Lights',
  'EMPR - Crystal Ball',
  'EMPR - Deep Blue',
  'EMPR - Electric Feel',
  'EMPR - Fireflies',
  'EMPR - Fractal Dreams',
  'EMPR - Glass Cathedral',
  'EMPR - Into The Deep',
  'EMPR - Liquid Motion',
  'EMPR - Magic Carpet',
  'EMPR - Night Sky',
  'EMPR - Ocean Waves',
  'EMPR - Psychedelic Sunrise',
  'EMPR - Quantum Realm',
  'EMPR - Star Gazer',
  'EMPR - Time Traveler',
  'EMPR - Underwater',
  'EMPR - Visions',
  'EMPR - Warp Gate',
  'EMPR - X-Ray',
  
  'ORB - Atlantis',
  'ORB - Biohazard',
  'ORB - Cosmic Journey',
  'ORB - Dark Matter',
  'ORB - Elemental Forces',
  'ORB - Firestorm',
  'ORB - Glass Bead Game',
  'ORB - Hypercube',
  'ORB - Ice Palace',
  'ORB - Jungle',
  'ORB - Kaleidoscope',
  'ORB - Lighthouse',
  'ORB - Matrix',
  'ORB - Neutron Star',
  'ORB - Orbit',
  'ORB - Plasma Ball',
  'ORB - Quantum Flux',
  'ORB - Radioactive',
  'ORB - Starship',
  'ORB - Technicolor',
  'ORB - Universe',
  'ORB - Vortex',
  'ORB - Warp Field',
  'ORB - Xenon',
  'ORB - Yellow Submarine',
  'ORB - Zen',
  
  // Community favorites
  'Community - Acid Rain',
  'Community - Aurora',
  'Community - Black Hole',
  'Community - Cloud Nine',
  'Community - Deep Purple',
  'Community - Electric Blue',
  'Community - Fire And Rain',
  'Community - Green Giant',
  'Community - Happy Trails',
  'Community - Ice Ice Baby',
  'Community - Jazz Fusion',
  'Community - Killer Instinct',
  'Community - Love Shack',
  'Community - Moonwalk',
  'Community - Neon Nights',
  'Community - Orange Crush',
  'Community - Purple Haze',
  'Community - Quantum Leap',
  'Community - Red Sky',
  'Community - Space Oddity',
  'Community - Technicolor Dream',
  'Community - Under Pressure',
  'Community - Violet Femme',
  'Community - White Rabbit',
  'Community - Xanadu',
  'Community - Yellow Brick Road',
  'Community - Ziggy Stardust',
]

// Generate extended preset collection
async function loadExtendedPresets() {
  if (isLoading) return loadPromise
  if (extendedKeys.length > 0) return { presets: extendedPresets, keys: extendedKeys }
  
  isLoading = true
  loadPromise = new Promise(async (resolve) => {
    // Start with base presets
    const basePkg = window.butterchurnPresets?.default ?? window.butterchurnPresets
    if (basePkg) {
      const basePresets = typeof basePkg.getPresets === 'function' ? basePkg.getPresets() : basePkg
      extendedPresets = { ...basePresets }
    }
    
    // Add quality preset entries (they'll reference the base presets or be placeholders)
    // In a real implementation, you'd load actual preset files
    // For now, we'll filter to only include presets that exist
    const availableKeys = Object.keys(extendedPresets)
    const qualityKeys = QUALITY_PRESETS.filter(key => availableKeys.includes(key))
    
    // Combine: quality presets first, then the rest
    const otherKeys = availableKeys.filter(key => !QUALITY_PRESETS.includes(key))
    extendedKeys = [...qualityKeys, ...otherKeys]
    
    console.log(`[Presets] Loaded ${extendedKeys.length} presets (${qualityKeys.length} quality, ${otherKeys.length} others)`)
    
    isLoading = false
    resolve({ presets: extendedPresets, keys: extendedKeys })
  })
  
  return loadPromise
}

export { loadExtendedPresets, extendedPresets, extendedKeys, QUALITY_PRESETS }
