openapi: 3.0.0
info:
  title: Sound Cistern Feed
  version: 1.0.0
paths:
  /feed:
    get:
      summary: Get user's Soundcloud feed
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of tracks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Track'
  /filter:
    post:
      summary: Filter feed by criteria
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FilterCriteria'
      responses:
        '200':
          description: Filtered list of tracks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Track'
components:
  schemas:
    Track:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        length:
          type: integer
        genre:
          type: string
        post_time:
          type: string
          format: date-time
    FilterCriteria:
      type: object
      properties:
        min_length:
          type: integer
        max_length:
          type: integer
        genres:
          type: array
          items:
            type: string
        start_date:
          type: string
          format: date-time
        end_date:
          type: string
          format: date-time
        query:
          type: string
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer